[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[project]
name = "nercone-fonts"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fonttools[unicode,woff]",
    "nercone-modern",
    "brotli",
    "zopfli",
    "py7zr"
]

[project.urls]
GitHub = "https://github.com/nercone-dev/fonts/"

[project.scripts]
nercone-fonts = "nercone_fonts.cli:main"

[dependency-groups]
dev = [
    "pytest>=8.3.5"
]
